- hosts: all
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "_"
        return: "301 https://$host$request_uri"
        filename: "nginx.cyber.range.80.conf"
      - listen: "443 ssl http2"
        server_name: "_"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "nginx.cyber.range.conf"
        root: "/var/www/hashiconf"
        index: "index.html"
        extra_parameters: |
          ssl_certificate      "/etc/ssl/cert/public.crt";
          ssl_certificate_key  "/etc/ssl/private/private.key";
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  tasks:
    - name: Ensure ssl folders exist
      file:
        path: /etc/ssl/cert
        state: directory

    - name: Copy public cert
      copy:
        src: cert/nginx-public.crt
        dest: /etc/ssl/cert/public.crt
    - name: Copy private key
      copy:
        src: cert/nginx-private.key
        dest: /etc/ssl/private/private.key
    - name: Ensure /var/www/ exists
      file:
        path: /var/www
        state: directory
    - name: clone repo
      git:
        repo: https://github.com/pezhore/hashiconf-demo-web.git
        dest: /var/www/hashiconf
  roles:
    - role: geerlingguy.nginx
  become: true
